apiVersion: v1
kind: Service
metadata:
  name: backend-clusterip-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: backend-port
  type: ClusterIP
