apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: frontend-port
      nodePort: 30000
  type: NodePort
